
var dummyData = { 
  "BCOMP" : {

    "Core_1" : [  "Core_1", 60,
      { "Code" :  "AMTH140", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Discrete Mathematics"},
      { "Code" :  "COSC110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Programming and the UNIX Environment"},
      { "Code" :  "COSC120", "CP" : "6", "TriAvail" : "12", "Prereq" : "null", "Name" : "Object Oriented Programming"},
      { "Code" :  "COSC210", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Database Management Systems"},
      { "Code" :  "COSC220", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Software Development Studio 2"},
      { "Code" :  "COSC230", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Data Structures and Algorithms"},
      { "Code" :  "COSC240", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Operating Systems"},
      { "Code" :  "COSC310", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Software Project Management"},
      { "Code" :  "COSC320", "CP" : "6", "TriAvail" : "12", "Prereq" : "null", "Name" : "Information Technology Project"},
      { "Code" :  "MTHS120", "CP" : "6", "TriAvail" : "12", "Prereq" : "null", "Name" : "Calculus and Linear Algebra 1"},
      ],
      "Core_2" : [  "Core_2", 6,
      { "Code" :  "COSC101", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Software Development Studio 1"},
      { "Code" :  "COSC102", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Data Science Studio 1"},
      ],
      "Core_3" : [  "Core_3", 6,
      { "Code" :  "MTHS130", "CP" : "6", "TriAvail" : "23", "Prereq" : "null", "Name" : "Calculus and Linear Algebra 2"},
      { "Code" :  "STAT100", "CP" : "6", "TriAvail" : "23", "Prereq" : "null", "Name" : "Introduction to Statistical Modelling"},
      ],
                        
    //"Major" : {

      "SOFTDEV002.5" : {
        "Prescribed_1" : [  "Prescribed_1", 6,
          { "Code" :  "COSC250", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Programming Paradigms"},
          { "Code" :  "COSC260", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Web Programming"},
          ],
        "Prescribed_2" : [  "Prescribed_2", 24,
          { "Code" :  "COSC330", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Parallel and Distributed Computing"},
          { "Code" :  "COSC340", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Computer Networks and Information Security"},
          { "Code" :  "COSC350", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Artificial Intelligence"},
          { "Code" :  "COSC360", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Advanced Web Programming"},
          { "Code" :  "COSC370", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "User Experience and Interaction Design"},
          ],
        "Listed" : [  "Listed", 30,
          { "Code" :  "AFM101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Financial Accounting"},
          { "Code" :  "AFM112", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Management Accounting"},
          { "Code" :  "AFM211", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Intermediate Financial Accounting"},
          { "Code" :  "AFM231", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Corporate Finance"},
          { "Code" :  "AFM242", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Financial Instruments and Markets"},
          { "Code" :  "AFM305", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Advanced Financial Accounting"},
          { "Code" :  "AFM319", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Auditing"},
          { "Code" :  "AFM322", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Small Business Finance"},
          { "Code" :  "BIOL110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biology I"},
          { "Code" :  "BIOL120", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biology II"},
          { "Code" :  "GENE210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Genetics"},
          { "Code" :  "GENE251/351", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Breeding and Genetics"},
          { "Code" :  "GENE322", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Genetics of Populations"},
          { "Code" :  "GENE352", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Genomic Analysis and Bioinformatics"},
          { "Code" :  "CHEM110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemistry I"},
          { "Code" :  "CHEM120", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemistry II"},
          { "Code" :  "CHEM204", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biological and Organic Chemistry"},
          { "Code" :  "CHEM210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Quantum and Thermal Structure"},
          { "Code" :  "CHEM220", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemical Reactivity"},
          { "Code" :  "CHEM250", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Analytical Chemistry"},
          { "Code" :  "CHEM302", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Organic Structure and Reactivity"},
          { "Code" :  "CHEM303", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Medicinal Chemistry"},
          { "Code" :  "CHEM305", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physical Chemistry"},
          { "Code" :  "THEA134", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Speaking in Public"},
          { "Code" :  "WRIT101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "The Craft of Academic Writing"},
          { "Code" :  "COSC301", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Special Topic in Computing"},
          { "Code" :  "COSC372", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Management Information Systems"},
          { "Code" :  "COSC380", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Algorithms in Machine Learning"},
          { "Code" :  "ECON101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Microeconomics"},
          { "Code" :  "ECON102", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Macroeconomics"},
          { "Code" :  "ECON201", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Intermediate Microeconomics"},
          { "Code" :  "ECON202", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Intermediate Macroeconomics"},
          { "Code" :  "ECON203", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Banking and Finance"},
          { "Code" :  "ECON311", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Contemporary Macroeconomic Issues"},
          { "Code" :  "ECON328", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Microeconomic Policy Evaluation"},
          { "Code" :  "ECON377", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Efficiency and Productivity Analysis"},
          { "Code" :  "LING101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Linguistics"},
          { "Code" :  "LING102", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Foundations of Linguistics"},
          { "Code" :  "LING365", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Phonetics and Phonology"},
          { "Code" :  "LING366", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Australia's Indigenous Languages"},
          { "Code" :  "AMTH250", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Programming in The Sciences"},
          { "Code" :  "MTHS110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Quantitative Skills with Applications"},
          { "Code" :  "PMTH212", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Multivariable Calculus"},
          { "Code" :  "PMTH213", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Linear Algebra"},
          { "Code" :  "PMTH331", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Topology"},
          { "Code" :  "PMTH332", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Abstract Algebra"},
          { "Code" :  "PMTH333", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Complex Analysis"},
          { "Code" :  "PMTH338", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Number Theory"},
          { "Code" :  "PMTH339", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Differential Equations"},
          { "Code" :  "PHYS131", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physics I"},
          { "Code" :  "PHYS132", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physics II"},
          { "Code" :  "PHYS204", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Electromagnetism 1"},
          { "Code" :  "PHYS207", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Fluid Mechanics"},
          { "Code" :  "PHYS211", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Electronics"},
          { "Code" :  "PHYS301", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Microscopic to Macroscopic Physics and Chemistry"},
          { "Code" :  "PHYS311", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Digital Electronic Systems"},
          { "Code" :  "PHYS313", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Photonics"},
          { "Code" :  "PSYC101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Psychology I"},
          { "Code" :  "PSYC102", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Psychology II"},
          { "Code" :  "PSYC206", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Cognitive Psychology"},
          { "Code" :  "SCI210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Scientific Programming"},
          { "Code" :  "SOCY100", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Sociology"},
          { "Code" :  "SOCY110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Foundations of Society"},
          { "Code" :  "SOCY313", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Social Policy"},
          { "Code" :  "SOCY345", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Mixed Methods in Social Research"},
          { "Code" :  "MATH260", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Probability and Simulation"},
          { "Code" :  "STAT210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Statistical Modelling and Experimental Design"},
          { "Code" :  "STAT270", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Inference"},
          { "Code" :  "STAT320", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Advanced Statistical Modelling"},
          { "Code" :  "STAT330", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Statistical Learning"},
          ],
      },

      "DATASC001.1" : {
        "Prescribed_1" : [  "Prescribed_1", 6,
          { "Code" :  "COSC250", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Programming Paradigms"},
          { "Code" :  "STAT210", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Statistical Modelling and Experimental Design"},
          ],
          "Prescribed_2" : [  "Prescribed_2", 24,
          { "Code" :  "COSC330", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Parallel and Distributed Computing"},
          { "Code" :  "COSC350", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Artificial Intelligence"},
          { "Code" :  "COSC380", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Algorithms in Machine Learning"},
          { "Code" :  "STAT330", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Statistical Learning"},
          ],
          "Listed" : [ "Listed", 30,
          { "Code" :  "BIOL110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biology I"},
          { "Code" :  "BIOL120", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biology II"},
          { "Code" :  "GENE210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Genetics"},
          { "Code" :  "GENE251/351", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Breeding and Genetics"},
          { "Code" :  "GENE322", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Genetics of Populations"},
          { "Code" :  "CHEM110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemistry I"},
          { "Code" :  "CHEM120", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemistry II"},
          { "Code" :  "CHEM204", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Biological and Organic Chemistry"},
          { "Code" :  "CHEM210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Quantum and Thermal Structure"},
          { "Code" :  "CHEM220", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Chemical Reactivity"},
          { "Code" :  "CHEM250", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Analytical Chemistry"},
          { "Code" :  "CHEM302", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Organic Structure and Reactivity"},
          { "Code" :  "CHEM303", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Medicinal Chemistry"},
          { "Code" :  "CHEM305", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physical Chemistry"},
          { "Code" :  "THEA134", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Speaking in Public"},
          { "Code" :  "WRIT101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "The Craft of Academic Writing"},
          { "Code" :  "COSC260", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Web Programming"},
          { "Code" :  "COSC301", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Special Topic in Computing"},
          { "Code" :  "COSC340", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Computer Networks and Information Security"},
          { "Code" :  "COSC360", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Advanced Web Programming"},
          { "Code" :  "COSC370", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "User Experience and Interaction Design"},
          { "Code" :  "COSC372", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Management Information Systems"},
          { "Code" :  "GEOL110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Geology and the Environment I"},
          { "Code" :  "GEOL120", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Geology and the Environment II"},
          { "Code" :  "EM333", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Spatial Analysis and Modelling"},
          { "Code" :  "EM334", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to GIS and Spatial Thinking"},
          { "Code" :  "EM336", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Remote Sensing and Image Analysis"},
          { "Code" :  "GEOL312", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Geophysics and Applied GIS for Earth Sciences"},
          { "Code" :  "LING101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Linguistics"},
          { "Code" :  "LING102", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Foundations of Linguistics"},
          { "Code" :  "LING365", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Phonetics and Phonology"},
          { "Code" :  "LING369", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Morphology and Syntax"},
          { "Code" :  "AMTH250", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Programming in The Sciences"},
          { "Code" :  "MTHS110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Quantitative Skills with Applications"},
          { "Code" :  "PMTH212", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Multivariable Calculus"},
          { "Code" :  "PMTH213", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Linear Algebra"},
          { "Code" :  "PMTH331", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Topology"},
          { "Code" :  "PMTH332", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Abstract Algebra"},
          { "Code" :  "PMTH333", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Complex Analysis"},
          { "Code" :  "PMTH338", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Number Theory"},
          { "Code" :  "PMTH339", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Differential Equations"},
          { "Code" :  "PHYS131", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physics I"},
          { "Code" :  "PHYS132", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Physics II"},
          { "Code" :  "PHYS204", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Electromagnetism 1"},
          { "Code" :  "PHYS207", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Fluid Mechanics"},
          { "Code" :  "PHYS211", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Electronics"},
          { "Code" :  "PHYS301", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Microscopic to Macroscopic Physics and Chemistry"},
          { "Code" :  "PHYS311", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Digital Electronic Systems"},
          { "Code" :  "PHYS313", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Applied Photonics"},
          { "Code" :  "PSYC101", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Psychology I"},
          { "Code" :  "PSYC102", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introductory Psychology II"},
          { "Code" :  "PSYC206", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Cognitive Psychology"},
          { "Code" :  "SCI210", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Scientific Programming"},
          { "Code" :  "SOCY100", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Introduction to Sociology"},
          { "Code" :  "SOCY110", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Foundations of Society"},
          { "Code" :  "SOCY313", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Social Policy"},
          { "Code" :  "SOCY345", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Mixed Methods in Social Research"},
          { "Code" :  "MATH260", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Probability and Simulation"},
          { "Code" :  "STAT270", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Inference"},
          { "Code" :  "STAT320", "CP" : "6", "TriAvail" : "123", "Prereq" : "null", "Name" : "Advanced Statistical Modelling"},
          ],
      },

    /*  "Double_Major" : {
        "Prescribed": [ 60,
          { "Code" :  "COSC250", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Programming Paradigms"},
          { "Code" :  "COSC260", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Web Programming"},
          { "Code" :  "STAT210", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Statistical Modelling and Experimental Design"},
          { "Code" :  "COSC330", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Parallel and Distributed Computing"},
          { "Code" :  "COSC340", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Computer Networks and Information Security"},
          { "Code" :  "COSC350", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Artificial Intelligence"},
          { "Code" :  "COSC360", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Advanced Web Programming"},
          { "Code" :  "COSC370", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "User Experience and Interaction Design"},
          { "Code" :  "COSC380", "CP" : "6", "TriAvail" : "2", "Prereq" : "null", "Name" : "Algorithms in Machine Learning"},
          { "Code" :  "STAT330", "CP" : "6", "TriAvail" : "1", "Prereq" : "null", "Name" : "Statistical Learning"},
          
        ]
      },*/
    //},
  },
  // end bCompSci

  "BN04" : {

    "Rule_A_F" : {
      "Prescribed" : [ "Prescribed", 144,
        { "Code" :  "HHSC111", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Science for Nurses 1"},
        { "Code" :  "HHSC112", "CP" : " 6 CP", "TriAvail" : "2", "Prereq" : " null", "Name" : " Science for Nurses 2"},
        { "Code" :  "HLTH101", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Information and Evidence in Health and Social Care"},
        { "Code" :  "HLTH102", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Interprofessional Practice in Health and Social Care"},
        { "Code" :  "HLTH103", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Communication for Health Professionals"},
        { "Code" :  "HLTH104", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " The Context of the Health and Community Services"},
        { "Code" :  "HSNS170", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Frameworks for Nursing Practice"},
        { "Code" :  "HSNS171", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Fundamentals of Nursing Practice 1"},
        { "Code" :  "HSNS173", "CP" : " 6 CP", "TriAvail" : "2", "Prereq" : " null", "Name" : " Fundamentals of Nursing Practice 2"},
        { "Code" :  "HSNS246", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 5: Primary and Community Health Care"},
        { "Code" :  "HSNS263", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 1"},
        { "Code" :  "HSNS264", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 2"},
        { "Code" :  "HSNS270", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 4"},
        { "Code" :  "HSNS273", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 6"},
        { "Code" :  "HSNS310", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 3: Mental Health Nursing"},
        { "Code" :  "HSNS362", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Transforming Nursing Practice 1"},
        { "Code" :  "HSNS363", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 2"},
        { "Code" :  "HSNS370", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 3: Nursing Older People"},
        { "Code" :  "HSNS373", "CP" : " 12 CP", "TriAvail" : "123", "Prereq" : " null", "Name" : " Transitioning to Practice 1"},
        { "Code" :  "HSNS374", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Clinical Leadership and Governance in Nursing"},
        { "Code" :  "HSNS376", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transitioning to Practice 2"},
        { "Code" :  "OORA200", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Working with Aboriginal People"},
      ],
    },

    "NMBA48" : {  //rule_b+e
      "Prescribed" : [ "Prescribed", 96, 
        { "Code" :  "HLTH101", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Information and Evidence in Health and Social Care"},
        { "Code" :  "HSNS246", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 5: Primary and Community Health Care"},
        { "Code" :  "HSNS263", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 1"},
        { "Code" :  "HSNS264", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 2"},
        { "Code" :  "HSNS270", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 4"},
        { "Code" :  "HSNS273", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 6"},
        { "Code" :  "HSNS310", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 3: Mental Health Nursing"},
        { "Code" :  "HSNS362", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Transforming Nursing Practice 1"},
        { "Code" :  "HSNS363", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 2"},
        { "Code" :  "HSNS370", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 3: Nursing Older People"},
        { "Code" :  "HSNS373", "CP" : " 12 CP", "TriAvail" : "123", "Prereq" : " null", "Name" : " Transitioning to Practice 1"},
        { "Code" :  "HSNS374", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Clinical Leadership and Governance in Nursing"},
        { "Code" :  "HSNS376", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transitioning to Practice 2"},
        { "Code" :  "OORA200", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Working with Aboriginal People"},
      ],
    },

    "BACHI42" :{  //rule_c
      "Prescribed" : [ "Prescribed", 102,
        { "Code" :  "HSNS207", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Foundations of Nursing in the Australian Context"},
        { "Code" :  "HSNS246", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 5: Primary and Community Health Care"},
        { "Code" :  "HSNS263", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 1"},
        { "Code" :  "HSNS264", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 2"},
        { "Code" :  "HSNS270", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 4"},
        { "Code" :  "HSNS273", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 6"},
        { "Code" :  "HSNS310", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 3: Mental Health Nursing"},
        { "Code" :  "HSNS362", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Transforming Nursing Practice 1"},
        { "Code" :  "HSNS363", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 2"},
        { "Code" :  "HSNS370", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 3: Nursing Older People"},
        { "Code" :  "HSNS373", "CP" : " 12 CP", "TriAvail" : "123", "Prereq" : " null", "Name" : " Transitioning to Practice 1"},
        { "Code" :  "HSNS374", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Clinical Leadership and Governance in Nursing"},
        { "Code" :  "HSNS376", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transitioning to Practice 2"},
        { "Code" :  "OORA200", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Working with Aboriginal People"},
      ],
    },

    "ENURS48": {  //rule_d
      "Prescribed" : [ "Prescribed", 108,
        { "Code" :  "HLTH101", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Information and Evidence in Health and Social Care"},
        { "Code" :  "HSNS207", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Foundations of Nursing in the Australian Context"},
        { "Code" :  "HSNS246", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 5: Primary and Community Health Care"},
        { "Code" :  "HSNS263", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 1"},
        { "Code" :  "HSNS264", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 2"},
        { "Code" :  "HSNS270", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 4"},
        { "Code" :  "HSNS273", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Integrated Nursing Practice 6"},
        { "Code" :  "HSNS310", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Integrated Nursing Practice 3: Mental Health Nursing"},
        { "Code" :  "HSNS362", "CP" : " 6 CP", "TriAvail" : "1", "Prereq" : " null", "Name" : " Transforming Nursing Practice 1"},
        { "Code" :  "HSNS363", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 2"},
        { "Code" :  "HSNS370", "CP" : " 6 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transforming Nursing Practice 3: Nursing Older People"},
        { "Code" :  "HSNS373", "CP" : " 12 CP", "TriAvail" : "123", "Prereq" : " null", "Name" : " Transitioning to Practice 1"},
        { "Code" :  "HSNS374", "CP" : " 6 CP", "TriAvail" : "13", "Prereq" : " null", "Name" : " Clinical Leadership and Governance in Nursing"},
        { "Code" :  "HSNS376", "CP" : " 12 CP", "TriAvail" : "23", "Prereq" : " null", "Name" : " Transitioning to Practice 2"},
        { "Code" :  "OORA200", "CP" : " 6 CP", "TriAvail" : "12", "Prereq" : " null", "Name" : " Working with Aboriginal People"},
      ],
    },
  },
  // end nursing

}